service: mobile-cloud

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  stage: dev
  region: us-east-1
  runtime: python3.8

resources:
  - ${file(./authentication/cognito-user-pool.yaml)}